doc: add notebook ci description
beta-team/beta-recsys pull request #308
Opened 2020-10-30 18:15 UTC by leungyukshing

2020-10-30 18:39 UTC, mengzaiqiao requested changes

2020-10-30 18:39 UTC, mengzaiqiao commented on docs/contribute/standardization-of-code-format-and-documentation.md
>  **The following examples are part of `demo.py`. For complete usages, please refer to [demo.py](https://github.com/beta-team/community/blob/master/demo.py).**
Update [demo.py](https://github.com/beta-team/community/blob/master/demo.py) link-->https://github.com/beta-team/community/blob/master/beta_recsys/demo.py

2020-10-31 05:25 UTC, Alva112358 approved these changes

2020-11-03 19:58 UTC, mengzaiqiao approved these changes

2020-11-03 19:58 UTC, merged